language: go

go:
 - 1.11.x
 - tip

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
  - export GOBIN=$HOME/bin PATH=$GOBIN:$PATH
  - go version
  - go get -t -v ./...

script:
  - go vet -all .
  - go build ./...
  - go test -race -v ./...
  - go get github.com/rjeczalik/bin/cmd/... github.com/rjeczalik/which/cmd/... github.com/rjeczalik/tools/cmd/... github.com/rjeczalik/bindata/cmd/bindata
  - gobin -u
